name: app-primes-g${NUM_GROUPS}-p${NUM_PARALLEL}
label: Prototype for Distributed Primes Calculation
cluster: ${CLUSTER}
parameters:
  initial_status: RUNNING

jobs:
  scatter:
    label: domain decomposition
    base_image: app-primes/scatter
    parameters:
      slot_on_head: yes
      start_message: ANY
    environments:
      - NUM_GROUPS=${NUM_GROUPS}
      - GROUP_SIZE=${GROUP_SIZE}
    sink_jobs:
      - calc

  calc:
    label: calc primes
    base_image: singularity/app-primes/calc.sif
    cluster: external-cluster
    environments:
      - LENGTH=${GROUP_SIZE}
    sink_jobs:
      - gather

  gather:
    label: Summary of results
    base_image: app-primes/gather
    parameters:
      slot_on_head: yes
    variables:
      # for session support
      # slot_options: always_running,reserved_on_exit
      sleep_seconds: 10
      max_sleep_count: 30
    environments:
      - NUM_GROUPS=${NUM_GROUPS}
