name: dir-copy.app
cluster: ${CLUSTER}
parameters:
  initial_status: RUNNING
  default_message_router: message-router

jobs:
  dir-list:
    base_image: hub.cstcloud.cn/scalebox/dir-list
    parameters:
      slot_on_head: yes
    variables:
      # 10 minutes
      max_sleep_count: 120
    command: docker run -d --rm --privileged --network=host {{ENVS}} {{VOLUMES}} {{IMAGE}}
    environments:
      - SOURCE_URL=${SOURCE_URL}
      - REGEX_FILTER=${REGEX_FILTER}
      - REGEX_2D_DATASET=${REGEX_DATASET}
      - INDEX_2D_DATASET=${INDEX_DATASET}

  rsync-copy:
    base_image: hub.cstcloud.cn/scalebox/rsync-copy
    parameters:
      slot_on_head: yes
    variables:
    # 10 minutes
      max_sleep_count: 120

  ftp-copy:
    base_image: hub.cstcloud.cn/scalebox/ftp-copy
    parameters:
      slot_on_head: yes
    variables:
    # 10 minutes
      max_sleep_count: 120

  message-router:
    base_image: dir-copy/message-router
    parameters:
      slot_on_head: yes
      start_message: ${DIR_NAME}
    variables:
    # 10 minutes
      max_sleep_count: 120
    sink_jobs:
     - dir-list
     - rsync-copy
     - ftp-copy
    