name: app-primes-g${NUM_GROUPS}-p${NUM_PARALLEL}
label: Prototype for Distributed Primes Calculation
cluster: ${CLUSTER}
parameters:
  initial_status: RUNNING

jobs:
  calc:
    label: calc primes
    base_image: app-primes/calc
    hosts:
      - ${CALC_HOST}:${NUM_PARALLEL}
    environments:
      - LENGTH=${GROUP_SIZE}
      - REMOTE_SERVER=${SERVER_1}
      - APP_ID=${APP_ID_1}
    sink_jobs:
      - gather
