name: scalebox.rsync-server
cluster: ${CLUSTER}
parameters:
  initial_status: RUNNING

jobs:
  rsyncd:
    base_image: hub.cstcloud.cn/scalebox/rsyncd
    schedule_mode: NODE
    parameters:
      start_message: ANY
    paths:
      - /:/local

  rsyncd-ssh:
    base_image: hub.cstcloud.cn/scalebox/rsyncd
    schedule_mode: NODE
    environments:
      - MODE=rsyncd-ssh
    parameters:
      start_message: ANY
    paths:
      - /:/local
