name: retry_test.test-app
cluster: local
parameters:
  initial_status: RUNNING

jobs:
  retry_test:
    base_image: hub.cstcloud.cn/scalebox/agent
    arguments:
      code_path: ${PWD}/code
      slot_options: slot_on_head
    parameters:
      start_message: 0
      retry_rules: "['1:3','2:2','*']"
    sink_jobs:
      - retry_test
