name: hello-scalebox.example.scalebox
cluster: local
parameters:
  initial_status: RUNNING

jobs:
  hello-scalebox:
    base_image: hub.cstcloud.cn/scalebox/agent:latest
    variables:
      code_path: ${PWD}/code
    parameters:
      slot_on_head: yes
      start_message: scalebox
