name: hello-scalebox.examples
cluster: local
parameters:
  initial_status: RUNNING

jobs:
  hello-scalebox:
    base_image: ${AGENT}
    arguments:
      code_path: ${PWD}/code
      slot_options: always_running,reserved_on_exit
    parameters:
      slot_on_head: yes
      start_message: scalebox
