name: hello-scalebox.example.scalebox
cluster: local
parameters:
  initial_status: RUNNING

jobs:
  hello-scalebox:
    base_image: hub.cstcloud.cn/scalebox/hello-scalebox
    schedule_mode: HEAD
    parameters:
      start_message: scalebox
