version: '3.8'
services:
  controld:
    image: hub.cstcloud.cn/scalebox/controld
    restart: unless-stopped
    container_name: controld
    # hostname: host1
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    depends_on:
     - database
    ports:
      - 50051:50051
      - 50061:8080
    environment:
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT}
      - LOG_LEVEL=WARN
      - TASK_POOL_BATCH_WRITE=yes
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/scalebox/log/controld:/tmp/scalebox/log/controld
      - /tmp/scalebox/controld-profile:/profile

  actuator:
    image: hub.cstcloud.cn/scalebox/actuator
    restart: unless-stopped
    container_name: actuator
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    environment:
      - GRPC_SERVER=controld:50051
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT}
      - LOG_LEVEL=WARN
      - LOCAL_ADDR=${LOCAL_ADDR}
      # for external cluster to start external slots
      - HEAD_SSH_USER=${USER}
      - HEAD_SSH_PORT=10022
      - TRACE_EXECUTOR=yes
    ports:
      - 50062:8080
    cap_add:
    #   update default route, for CentOS8
      - NET_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/scalebox/log/actuator:/tmp/scalebox/log/actuator
      - /tmp/scalebox/actuator-profile:/profile
    # for k8s
      - ${HOME}/.kube:/root/.kube
    depends_on:
      - controld

  database:
    image: hub.cstcloud.cn/scalebox/database
    restart: unless-stopped
    container_name: database
    # Set postgresql max connections at runtime
    # command: postgres -c 'max_connections=800'
    environment:
#      - TZ='GMT-8'
#      - PGTZ='GMT-8'
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
#      - /etc/scalebox/my-postgresql.conf:/etc/scalebox/my-postgresql.conf:ro
      - pgdata:/var/lib/postgresql/data
#      - /opt/docker-volumes/pgdata:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    shm_size: 8g
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "scalebox"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
