name: app-primes-g${NUM_GROUPS}-p${NUM_PARALLEL}
label: Prototype for Distributed Primes Calculation
cluster: ${CLUSTER}
parameters:
  initial_status: RUNNING

jobs:
  scatter:
    label: domain decomposition
    base_image: app-primes/scatter
    schedule_mode: HEAD
    parameters:
      start_message: ANY
    variables:
      repeated: yes
    environments:
      - NUM_GROUPS=${NUM_GROUPS}
      - GROUP_SIZE=${GROUP_SIZE}
    sink_jobs:
      - calc

  calc:
    label: calc primes
    base_image: app-primes/calc
    # schedule_mode: HEAD
    hosts:
      - ${CALC_HOST}:${NUM_PARALLEL}
    parameters:
      tasks_per_queue: 500
    environments:
      - LENGTH=${GROUP_SIZE}
    sink_jobs:
      - gather

  gather:
    label: Summary of results
    base_image: app-primes/gather
    schedule_mode: HEAD
    environments:
      - NUM_GROUPS=${NUM_GROUPS}
    variables:
      # should be 'yes', to support session
      repeated: yes
