name: app-primes-g${NUM_GROUPS}-p${NUM_PARALLEL}
label: Prototype for Distributed Primes Calculation
cluster: ${CLUSTER}
parameters:
  initial_status: RUNNING

jobs:
  scatter:
    label: domain decomposition
    base_image: hub.cstcloud.cn/scalebox/agent
    variables:
      code_path: ${PWD}/scatter/code
      slot_options: slot_on_head
    parameters:
      start_message: ANY
    environments:
      - NUM_GROUPS=${NUM_GROUPS}
      - GROUP_SIZE=${GROUP_SIZE}
    sink_jobs:
      - calc

  calc:
    label: calc primes
    base_image: app-primes/calc
    hosts:
      - ${CALC_HOST}:${NUM_PARALLEL}
    parameters:
      bulk_message_size: 10
      task_cache_expired_minutes: 60
    environments:
      - LENGTH=${GROUP_SIZE}
    sink_jobs:
      - gather

  gather:
    label: Summary of results
    base_image: hub.cstcloud.cn/scalebox/agent
    variables:
      code_path: ${PWD}/gather/code
      sleep_seconds: 10
      max_sleep_count: 100
      slot_options: slot_on_head
      # slot_options: always_running,reserved_on_exit
    parameters:
      bulk_message_size: 100
    environments:
      - NUM_GROUPS=${NUM_GROUPS}
