name: file-copy.scalebox
cluster: ${CLUSTER}
parameters:
  initial_status: RUNNING

jobs:
  list-dir:
    base_image: hub.cstcloud.cn/scalebox/list-dir
    schedule_mode: HEAD
    command: docker run -d --rm --privileged --network=host {{ENVS}} {{VOLUMES}} {{IMAGE}}
    variables:
      always_running: yes
    parameters:
      key_group_regex: ^(.+)$
      start_message: ${DIR_NAME}
    paths:
      - /:/local:ro
    environments:
      - SOURCE_URL=${SOURCE_URL}
      - REGEX_FILTER=${REGEX_FILTER}
    sink_jobs:
      - file-copy

  file-copy:
    base_image: hub.cstcloud.cn/scalebox/ftp-copy
    # schedule_mode: HEAD
    command: docker run -d --privileged --rm --network=host {{ENVS}} {{VOLUMES}} {{IMAGE}}
    hosts:
      - h0:4
    # variables:
    #   always_running: yes
    parameters:
      retry_rules: "['14:${N_RETRIES}','15:${N_RETRIES}']"
      key_group_regex: ${KEY_GROUP_REGEX}
      key_group_submatch: ${KEY_GROUP_SUBMATCH}
    environments:
      - SOURCE_URL=${SOURCE_URL}
      - TARGET_URL=${TARGET_URL}
      - ACTION=${ACTION}
      - ENABLE_LOCAL_RELAY=${ENABLE_LOCAL_RELAY}
      - RAM_DISK_GB=
    paths:
      - /:/local
