name: file-copy.scalebox
cluster: ${CLUSTER}
# parameters:
#   initial_status: RUNNING

jobs:
  list-dir:
    base_image: hub.cstcloud.cn/scalebox/list-dir
    schedule_mode: HEAD
    variables:
      reserved_on_exit: yes
    parameters:
      key_group_regex: ^(.+)$
      start_message: ${DIR_NAME}
    paths:
      - /:/local:ro
    environments:
      - SOURCE_URL=${SOURCE_URL}
      - REGEX_FILTER=${REGEX_FILTER}
      - RSYNC_PASSWORD=${RSYNC_PASSWORD}
    sink_jobs:
      - file-copy

  file-copy:
    base_image: hub.cstcloud.cn/scalebox/rsync-copy
    schedule_mode: HEAD
    parameters:
      key_group_regex: ^([^/]+)/.+$
    environments:
      - SOURCE_URL=${SOURCE_URL}
      - TARGET_URL=${TARGET_URL}
      - ENABLE_LOCAL_RELAY=${ENABLE_LOCAL_RELAY}
      - RSYNC_PASSWORD=${RSYNC_PASSWORD}
    paths:
      - /:/local
