name: timeout-gen.test-app
cluster: local
parameters:
  initial_status: RUNNING

jobs:
  timeout-gen:
    base_image: timeout-gen
    parameters:
      start_message: 0
    arguments:
      task_timeout_seconds:	10
    schedule_mode: HEAD
    environments:
      - SLEEP_SECONDS=20
