name: hello-scalebox.singularity
cluster: local
parameters:
  initial_status: RUNNING

jobs:
  hello-scalebox:
    base_image: singularity/scalebox/hello-scalebox.sif
    # schedule_mode: HEAD
    parameters:
      start_message: scalebox
    # command: singularity run {{ENVS}} {{VOLUMES}} docker://{{IMAGE}}
