name: hello-scalebox.singularity
cluster: local
parameters:
  initial_status: RUNNING

jobs:
  hello-scalebox:
    base_image: singularity/scalebox/hello-scalebox.sif
    parameters:
      slot_on_head: yes
      start_message: scalebox
